apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-{{ .Values.image.flaskApp.env }}
  labels:
    app: flask-app-{{ .Values.image.flaskApp.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app-{{ .Values.image.flaskApp.env }}
  template:
    metadata:
      labels:
        app: flask-app-{{ .Values.image.flaskApp.env }}
    spec:
      containers:
      - name: flask-app-{{ .Values.image.flaskApp.env }}
        image: "{{ .Values.image.flaskApp.repository }}:{{ .Values.image.flaskApp.tag }}"
        ports:
        - containerPort: {{ .Values.service.flaskAppPort }}
        env:
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_APP
          value: "src/app.py"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
