apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twitch-stream-planner-ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: alb
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: nginx-proxy-{{ .Values.image.nginx.env }}
            port:
              number: {{ $.Values.service.nginxProxyPort }}
      {{- end }}
  {{- end }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  {{- end }}
