apiVersion: v1
kind: Service
metadata:
  name: flask-app-{{ .Values.image.flaskApp.env }}
  labels:
    app: flask-app-{{ .Values.image.flaskApp.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.flaskAppPort }}
      targetPort: {{ .Values.service.flaskAppPort }}
      protocol: TCP
      name: http
  selector:
    app: flask-app-{{ .Values.image.flaskApp.env }}
