apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.flaskAppPort }}
      targetPort: {{ .Values.service.flaskAppPort }}
      protocol: TCP
      name: http
  selector:
    app: flask-app
