apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.nginxProxyPort }}
      targetPort: {{ .Values.service.nginxProxyPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.nginxProxyPortSecure }}
      targetPort: {{ .Values.service.nginxProxyPortSecure }}
      protocol: TCP
      name: https
  selector:
    app: nginx-proxy
